export const ROUTE_PATHS = {
  onboarding: {
    root: '/onboarding',
    getStarted: '/onboarding',
    register: '/onboarding/register',
    verifyOtp: '/onboarding/verify-otp',
    claimPortal: '/onboarding/claim-workspace',
    setPassword: '/onboarding/set-password',
    success: '/onboarding/success',
    findCompany: '/onboarding/find-company',
  },
  auth: {
    login: '/login',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
  },
  dashboard: '/dashboard',
  acceptInvite: '/accept-invite',
  sales: '/sales',
  purchase: '/purchase',
  inventory: '/inventory',
  production: '/production',
  accounts: '/accounts',
  crm: '/crm',
  hr: '/hr',
  reports: '/reports',
  help: '/help',
  settings: {
    users: '/settings/users',
    userDetail: (id: number | string) => `/settings/users/${id}`,
    roles: '/settings/roles',
    permissions: '/settings/permissions',
  },
} as const;
